name: 'Goframe cli toolkit'
description: 'Get started with goframe cli toolkit'
author: 'GitHub'
inputs: 
  cmd:
    description: 'cmd'
    default: 'help'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
